insert m v
    | isSingle v = case m of
        "" -> [v]
        "h" -> [v++m, v++m++v]
        "y" -> [v++m]
        "w" -> [v++m]
        "’" -> [v++m, v++m++v]
        "’h" -> [v++m, v++m++v]
        "’y" -> [v++m]
        "’w" -> [v++m]
        _ -> [v]
    | isIDi[p]hthong v = let (q:p:_) = v in case m of
        "" -> [v]
        "h" -> [v++m, v++m++[q]]
        "y" -> [[q]++m++[p]]
        "w" -> [v++m++[q]]
        "’" -> [v++m, v++m++[q]]
        "’h" -> [v++m, v++m++[q]]
        "’y" -> [[q]++m++[p]]
        "’w" -> [v++m++[q]]
        _ -> [v]
    | isUDi[p]hthong v = let (q:p:_) = v in case m of
        "" -> [v]
        "h" -> [v++m, v++m++[q]]
        "y" -> [v++m++[q]]
        "w" -> [[q]++m++[p]]
        "’" -> [v++m, v++m++[q]]
        "’h" -> [v++m, v++m++[q]]
        "’y" -> [v++m++[q]]
        "’w" -> [[q]++m++[p]]
        _ -> [v]
    | isDisjunct v = let (q:p:_) = v in case m of
        "" -> [v]
        "h" -> [[q]++m++[p]]
        "y" -> [[q]++m++[p]]
        "w" -> [[q]++m++[p]]
        "’" -> [[q]++m++[p]]
        "’h" -> [[q]++m++[p]]
        "’y" -> [[q]++m++[p]]
        "’w" -> [[q]++m++[p]]
        _ -> [v]
    | _ = error "unknown insert"